# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-29 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selfid', models.CharField(max_length=30, unique=True)),
                ('url', models.URLField(unique=True)),
                ('title', models.TextField(blank=True)),
                ('authors', models.TextField(blank=True)),
                ('abstract', models.TextField(blank=True)),
                ('years', models.TextField(blank=True)),
                ('sources', models.TextField(blank=True)),
                ('doi', models.TextField(blank=True)),
                ('publication', models.TextField(blank=True)),
                ('fields', models.TextField(blank=True)),
                ('referids', models.TextField(blank=True)),
                ('citeids', models.TextField(blank=True)),
            ],
        ),
    ]
