# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-30 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reference',
            old_name='years',
            new_name='year',
        ),
        migrations.AlterField(
            model_name='reference',
            name='url',
            field=models.TextField(blank=True),
        ),
    ]
